import { TranscriptData } from '@/types/student';

export const sampleTranscript: TranscriptData = {
  profile: {
    studentName: 'Matti Meikäläinen',
    studentNumber: '015123456',
    degreeProgramme: 'Tietojenkäsittelytieteen kandiohjelma (BSc Computer Science)',
    studyStartDate: '2021-08-01',
    targetCredits: 180,
    nominalPace: 60,
  },
  courses: [
    // Year 1 - Fall 2021
    {
      id: 'c-1',
      code: 'TKT10001',
      name: 'Ohjelmoinnin perusteet (Introduction to Programming)',
      credits: 5,
      grade: '5',
      date: '2021-10-15',
      passed: true,
      level: 'Perusopinnot',
    },
    {
      id: 'c-2',
      code: 'TKT10002',
      name: 'Ohjelmoinnin jatkokurssi (Advanced Programming)',
      credits: 5,
      grade: '4',
      date: '2021-12-18',
      passed: true,
      level: 'Perusopinnot',
    },
    {
      id: 'c-3',
      code: 'MAT11001',
      name: 'Johdatus yliopistomatematiikkaan',
      credits: 5,
      grade: '3',
      date: '2021-12-20',
      passed: true,
      level: 'Matematiikka',
    },
    // Year 1 - Spring 2022
    {
      id: 'c-4',
      code: 'TKT10003',
      name: 'Tietokantojen perusteet (Database Systems)',
      credits: 5,
      grade: '5',
      date: '2022-03-10',
      passed: true,
      level: 'Perusopinnot',
    },
    {
      id: 'c-5',
      code: 'TKT10004',
      name: 'Tietokoneen toiminta (Computer Organization)',
      credits: 5,
      grade: '4',
      date: '2022-05-15',
      passed: true,
      level: 'Perusopinnot',
    },
    {
      id: 'c-6',
      code: 'KK-ENG301',
      name: 'Academic and Professional Communication in English',
      credits: 4,
      grade: 'HYV',
      date: '2022-05-20',
      passed: true,
      level: 'Kieliopinnot',
    },
    {
      id: 'c-7',
      code: 'MAT11002',
      name: 'Lineaarialgebra ja matriisilaskenta I',
      credits: 5,
      grade: '4',
      date: '2022-06-01',
      passed: true,
      level: 'Matematiikka',
    },

    // Year 2 - Fall 2022
    {
      id: 'c-8',
      code: 'TKT20001',
      name: 'Tietorakenteet ja algoritmit (Data Structures & Algorithms)',
      credits: 10,
      grade: '5',
      date: '2022-10-25',
      passed: true,
      level: 'Aineopinnot',
    },
    {
      id: 'c-9',
      code: 'TKT20002',
      name: 'Ohjelmistotuotanto (Software Engineering)',
      credits: 5,
      grade: '5',
      date: '2022-12-15',
      passed: true,
      level: 'Aineopinnot',
    },
    {
      id: 'c-10',
      code: 'MAT11003',
      name: 'Diskreetti matematiikka I',
      credits: 5,
      grade: '4',
      date: '2022-12-20',
      passed: true,
      level: 'Matematiikka',
    },

    // Year 2 - Spring 2023
    {
      id: 'c-11',
      code: 'TKT20003',
      name: 'Käyttöjärjestelmät (Operating Systems)',
      credits: 5,
      grade: '4',
      date: '2023-03-12',
      passed: true,
      level: 'Aineopinnot',
    },
    {
      id: 'c-12',
      code: 'TKT20004',
      name: 'Tietoliikenteen perusteet (Computer Networks)',
      credits: 5,
      grade: '5',
      date: '2023-05-10',
      passed: true,
      level: 'Aineopinnot',
    },
    {
      id: 'c-13',
      code: 'TKT20005',
      name: 'Laskennan mallit (Models of Computation)',
      credits: 5,
      grade: '3',
      date: '2023-05-25',
      passed: true,
      level: 'Aineopinnot',
    },
    {
      id: 'c-14',
      code: 'KK-RUO001',
      name: 'Svenska för akademiska studier (Swedish for Academic Studies)',
      credits: 3,
      grade: 'HYV',
      date: '2023-06-05',
      passed: true,
      level: 'Kieliopinnot',
    },

    // Year 3 - Fall 2023
    {
      id: 'c-15',
      code: 'TKT20006',
      name: 'Tekoälyn perusteet (Introduction to AI)',
      credits: 5,
      grade: '5',
      date: '2023-10-18',
      passed: true,
      level: 'Aineopinnot',
    },
    {
      id: 'c-16',
      code: 'TKT20007',
      name: 'Ohjelmistotuotantoprojekti (Software Engineering Project)',
      credits: 10,
      grade: '5',
      date: '2023-12-15',
      passed: true,
      level: 'Aineopinnot',
    },
    {
      id: 'c-17',
      code: 'FYS2001',
      name: 'Fysiikan perusteet sivuaineena',
      credits: 5,
      grade: '3',
      date: '2023-12-22',
      passed: true,
      level: 'Sivuaine',
    },

    // Year 3 - Spring 2024
    {
      id: 'c-18',
      code: 'TKT20008',
      name: 'Full Stack Open (Web Application Development)',
      credits: 10,
      grade: '5',
      date: '2024-03-20',
      passed: true,
      level: 'Aineopinnot',
    },
    {
      id: 'c-19',
      code: 'TKT20009',
      name: 'Pilvipalvelut ja DevOps (Cloud & DevOps)',
      credits: 5,
      grade: '5',
      date: '2024-05-15',
      passed: true,
      level: 'Aineopinnot',
    },
    {
      id: 'c-20',
      code: 'TKT20010',
      name: 'Kyberturvallisuuden perusteet (Cyber Security)',
      credits: 5,
      grade: '4',
      date: '2024-05-30',
      passed: true,
      level: 'Aineopinnot',
    },

    // Year 4 - Fall 2024
    {
      id: 'c-21',
      code: 'TKT20011',
      name: 'Kandidaatintutkielma ja seminaari (BSc Thesis & Seminar)',
      credits: 10,
      grade: '5',
      date: '2024-11-20',
      passed: true,
      level: 'Tutkielma',
    },
    {
      id: 'c-22',
      code: 'TKT20012',
      name: 'Kypsyysnäyte (Maturity Test)',
      credits: 0,
      grade: 'HYV',
      date: '2024-11-25',
      passed: true,
      level: 'Tutkielma',
    },
    {
      id: 'c-23',
      code: 'CS-E4000',
      name: 'Koneoppiminen (Machine Learning)',
      credits: 5,
      grade: '5',
      date: '2024-12-18',
      passed: true,
      level: 'Syventävät',
    },
    {
      id: 'c-24',
      code: 'TKT30001',
      name: 'Hajautetut järjestelmät (Distributed Systems)',
      credits: 5,
      grade: '4',
      date: '2025-01-15',
      passed: true,
      level: 'Syventävät',
    },
  ],
};
